# This program was written to automate on a large scale the statistical analyses
# done in R, in order to save time - so that minor changes to analytical processes
# may be quickly reflected across the entire analysis. This allows hours of work
# to be repeated, with or without changes, in less than two minutes while analyzing 
# thousands of datapoints.
#
# The program is interspersed with diagnostic output messages ("cat(...)") that 
# output to the console and indicate the progression of the program.
# 
# Contact gangres@nevada.unr.edu for questions regarding the code's function and 
# behavior.

 

#Establish working directory with target files.

cat("Setting Working Directory...\n")
setwd("C:\\Users\\gjang\\Documents\\GitHub\\CAI-Analysis-Script")

SWITCHBOARD.DIRECTORY <-
  "C:\\Users\\gjang\\Documents\\GitHub\\CAI-Analysis-Script\\Script-v2"

#Load relevant packages into library

cat("Loading Packages...\n")
library("dplyr")
library("tibble")
library("rsq")
library("car")
library("Rcmdr")
library("hash")
library("multcompView")
library("HyperG")
library("plotly")
library("htmlwidgets")
library("magrittr")
library("tidyr")
library("multiApply")
library("stringr")

library("viridis")
library("pheatmap")
library(RColorBrewer)
#library("roxygen2")

# SWITCHBOARD variable/function setup to quickly adjust elements present throughout the program.
# Hacky way of getting consistent legend generation, also controls value rounding over the program
#   and some constant definitions
# This section provides a component of automation - allowing changes to common 
# elements throughout the program to be made in a centralized manner that propagates 
# to all functions and codeblocks which use that information.

#   Dataset over which analysis is done.
cat("Loading Dataset of Interest...\n")
SWITCHBOARD.csvMAINFILE <- read.csv(file = 'PARL0_06202022.csv')

#put below code in CALC.AUGMENT()

SWITCHBOARD.csvAUGMFILE <- SWITCHBOARD.csvMAINFILE %>%
  mutate(H_div_W = height / width,
         FW_div_W = fresh_weight / width,
         FW_div_D = fresh_weight / diameter,
         FW_div_H = fresh_weight / height,
         FW_div_T = fresh_weight / thickness,
         D_div_W = diameter / width) %>%
  merge(read.csv('Pad_Area_Estimations.csv', fileEncoding = 'UTF-8-BOM'), by = "completeID") %>%
  mutate(Theo_Area = pi*height*width*0.25) %>%
  mutate(PartRatio = ((height-width)/(height+width))^2) %>%
  mutate(Pade_Peri = pi*(height+width)*(64-3*PartRatio^2)/(64-16*PartRatio)) %>%
  mutate(Pade_Derived_Diam = Pade_Peri/pi)



# names(SWITCHBOARD.csvAUGMFILE) >> 
# [1] "completeID"   "fresh_weight" "width"        "height"       "diameter"    
# [6] "thickness"    "accession"    "species"      "H_div_W"      "FW_div_W"    
# [11] "FW_div_D"     "FW_div_H"     "FW_div_T"     "D_div_W"      "Area"   

cat("::| Setting Accession List\n")
SWITCHBOARD.ACCESSIONLIST <- c(242, 246, 319, 325, 326, 390, 572, 580, 582, 584, 585, 839, 845, 854)

cat("::| Setting Autogenerated Intermeasure Regression Figure Axes\n")
DATA_OBJECTS.MODELS_intermeasure <- tribble(
  ~ xname, ~ yname,
  'width',     'fresh_weight',
  'height',    'fresh_weight',
  'diameter',  'fresh_weight',
  'thickness', 'fresh_weight',
  'width',     'height',
  'width',     'diameter',
  'width',     'thickness',
  'height',    'diameter',
  'height',    'thickness',
  'diameter',  'thickness',
)

SWITCHBOARD.models_intermeasure_abbr <- c("FW~W", "FW~H", "FW~D", "FW~T", "H~W", "D~W", "T~W", "D~H", "T~H", "T~D")

cat("::| Setting QQ Plot measures\n")
SWITCHBOARD.qqMeasures_VEC <- c("width", "diameter", "height", "thickness", "fresh_weight")

cat("::| Setting Autogenerated Multiplicative Model Regression Figure Axes\n")
SWITCHBOARD.models_multiplicative <- c(
  "fresh_weight~width",
  "fresh_weight~height",
  "fresh_weight~diameter",
  "fresh_weight~thickness",
  "fresh_weight~D_div_W",
  "fresh_weight~width+height",
  "fresh_weight~width*height",
  "fresh_weight~width+diameter",
  "fresh_weight~width*diameter",
  "fresh_weight~width+thickness",
  "fresh_weight~width*thickness",
  "fresh_weight~height+diameter",
  "fresh_weight~height*diameter",
  "fresh_weight~height+thickness",
  "fresh_weight~height*thickness",
  "fresh_weight~diameter+thickness",
  "fresh_weight~diameter*thickness",
  "fresh_weight~width+height+diameter",
  "fresh_weight~width*height*diameter",
  "fresh_weight~width+height+thickness",
  "fresh_weight~width*height*thickness",
  "fresh_weight~width+diameter+thickness",
  "fresh_weight~width*diameter*thickness",
  "fresh_weight~height+diameter+thickness",
  "fresh_weight~height*diameter*thickness",
  "fresh_weight~width+height+diameter+thickness",
  "fresh_weight~width*height*diameter*thickness"
  #"I(width*height*diameter*thickness)"
)

SWITCHBOARD.models_multiplicative_abbr <- c(
  "FW~W",
  "FW~H",
  "FW~D",
  "FW~T",
  "FW~D/W",
  "FW~W+H",
  "FW~W*H",
  "FW~W+D",
  "FW~W*D",
  "FW~W+T",
  "FW~W*T",
  "FW~H+D",
  "FW~H*D",
  "FW~H+T",
  "FW~H*T",
  "FW~D+T",
  "FW~D*T",
  "FW~W+H+D",
  "FW~W*H*D",
  "FW~W+H+T",
  "FW~W*H*T",
  "FW~W+D+T",
  "FW~W*D*T",
  "FW~H+D+T",
  "FW~H*D*T",
  "FW~W+H+D+T",
  "FW~W*H*D*T"
  #"I(width*height*diameter*thickness)"
)

cat("::| Setting Autogenerated Elliptical Model Regression Figure Axes\n")
SWITCHBOARD.models_elliptical <- c(
  "fresh_weight~Area",
  "fresh_weight~Theo_Area",
  "fresh_weight~Area+thickness",
  "fresh_weight~Area*thickness",
  "fresh_weight~Theo_Area+thickness",
  "fresh_weight~Theo_Area*thickness",
  "fresh_weight~Theo_Area+thickness+Pade_Derived_Diam",
  "fresh_weight~Theo_Area*thickness*Pade_Derived_Diam"
)

SWITCHBOARD.models_elliptical_abbr <- c(
  "FW~A",
  "FW~Th_A",
  "FW~A+T",
  "FW~A*T",
  "FW~Th_A+T",
  "FW~Th_A*T",
  "FW~Th_A+T+PDD",
  "FW~Th_A*T*PDD"
)


cat("::| Generating Model Guides\n")
DATA_OBJECTS.MODELS_intermeasure$models <- apply(DATA_OBJECTS.MODELS_intermeasure[, c("yname", "xname")], 1, paste, collapse = "~") 

DATA_OBJECTS.MODELS_multiplicative <- as.data.frame(SWITCHBOARD.models_multiplicative) %>%
  set_colnames(c("models"))

DATA_OBJECTS.MODELS_elliptical <- as.data.frame(SWITCHBOARD.models_elliptical) %>%
  set_colnames(c("models"))

#DATA_OBJECTS.MODELS_intermeasure



# CALC.ModelGenerator <- function(df_in, fill_models_df) {
#   fits_frame <- data.frame(accession = SWITCHBOARD.ACCESSIONLIST)
#   for(model in fill_models_df$models) {
#     new_models <- df_in %>%
#       group_by(accession) %>%
#       do(model = lm(model, data = .)) %>%
#       setNames(c("accession", model)) %>%
#       column_to_rownames("accession")
#     fits_frame <- cbind(fits_frame, new_models[model])
#   }
#   return(fits_frame)
# }





DEBUGG.Leverage <- function(model_df) {
  return_model <- model_df
  #print(names(model_df))
  for (col in 2:ncol(return_model)) {
    #print(names(return_model[col]))
    for (row in 1:nrow(return_model)) {
      #print(CALC.ModelIndexHighLeverage(return_model[row, col][[1]]))
      #return_model[row, col] <- CALC.ModelHighLeverage(return_model[row, col][[1]])
    }
  }
  #return(return_model)
}



#FIGURE OUT HOW TO ITERATIVELY FILTER OUT THE DATAPOINTS BASED ON HIGH LEVERAGE 3*P/N

#Creating initial linear regressions object

cat("::| Generating Model Dataframes\n")
DATA_OBJECTS.LinearRegressions_DF <- CALC.ModelGenerator(SWITCHBOARD.csvAUGMFILE, DATA_OBJECTS.MODELS_intermeasure)
DATA_OBJECTS.MultiplicativeRegressions_DF_UNFILT <- CALC.ModelGenerator(SWITCHBOARD.csvAUGMFILE, DATA_OBJECTS.MODELS_multiplicative)
DATA_OBJECTS.EllipticalRegressions_DF_UNFILT <- CALC.ModelGenerator(SWITCHBOARD.csvAUGMFILE, DATA_OBJECTS.MODELS_elliptical)

# MAKER.BoxplotMaker <- function(dataset, measure, colors) {
#   TUKEY <- CALC.tukeyTester(dataset, measure)
#   LABELS <- CALC.tukeyLabel_DF(TUKEY)
#   target_boxplot <- boxplot(dataset[[measure]] ~ dataset$accession, ylim=c(min(dataset[[measure]]) , 1.1*max(dataset[[measure]])) , col=colors[as.numeric(LABELS[,1])] , ylab="value" , main="")
#   target_boxplot
#   return(target_boxplot)
# }

#MAKER.BoxplotMaker(SWITCHBOARD.csvAUGMFILE, "height", EXAMPLE_COLORS)

#---------------------
#COMPILE.tukeygraphs(SWITCHBOARD.csvAUGMFILE)

#]]DEBUG
#GRAPHER.tukeyHypergraph(CALC.tukeyTester(SWITCHBOARD.csvAUGMFILE, "height"), "height")




test_mult_model <- CALC.ModelFetch(DATA_OBJECTS.EllipticalRegressions_DF_UNFILT, 242, "fresh_weight~Theo_Area*thickness*Pade_Derived_Diam")
test_model <- CALC.ModelFetch(DATA_OBJECTS.LinearRegressions_DF, 242, "fresh_weight~height")



# # MAINFILE | QQ Plots
# cat("::| Compiling QQ Plots (MAINFILE)\n")
# COMPILE.qqGen(SWITCHBOARD.csvMAINFILE)
# 
# # INTERMEASURE | Intermeasure
# cat("::| Compiling Intermeasure Plots (MAINFILE)\n")
# COMPILE.intermeasure(DATA_OBJECTS.LinearRegressions_DF)
# 
# # MAINFILE | Tukey Intercomparison Plots
# cat("::| Compiling Tukey Intercomparison Plots (MAINFILE)\n")
# COMPILE.tukeygraphs(SWITCHBOARD.csvMAINFILE)

# INTERMEASURE | SBC Heatmap

# R^2 Heatmap

# Hardtables SBC

# Hardtables R^2

cat("::| Generating Filter Dataset on 3p/n threshold value by model\n")

# for (accession in SWITCHBOARD.ACCESSIONLIST) {
#   print(accession)
#   print("C")
#   row_iter <- DATA_OBJECTS.LinearRegressions_DF[which(rownames(DATA_OBJECTS.LinearRegressions_DF) == accession),]
#   print("1")
#   print(row_iter)
#   for (model in row_iter) {
#     print("2")
#     print(model)
#     high_loc <- CALC.ModelIndexHighLeverage(model[[1]])
#     print("3")
#     for (loc in high_loc) {
#       DATA_OBJECTS.BLACKLIST_3PN <- CALC.ModelValuePairsFromIndex(loc, model) %>%
#         CALC.PadIDfromModelValuePairs(DATA_OBJECTS.LinearRegressions_DF, accession) %>%
#         append(DATA_OBJECTS.BLACKLIST_3PN, .) %>%
#         unique()
#     }
#   }
# }

UTIL.Assemble3PNDroplist <- function(fits_df, data_df) {
  blacklist_3pn <- c()
  
  for (modelname in colnames(fits_df)[-1]) {
    
    for (accession in SWITCHBOARD.ACCESSIONLIST) {
      
      model <- CALC.ModelFetch(fits_df, accession, modelname)
      target_loc <- CALC.ModelIndexHighLeverage(model)
      
      for (loc in target_loc) {
        pairframe <- CALC.ModelValuePairsFromIndex(loc, model)
        modelID <- CALC.PadIDfromModelValuePairs(pairframe, data_df, accession) 
        blacklist_3pn <- c(blacklist_3pn, modelID)
      }
    }
  }
  blacklist_3pn <- sort(unique(blacklist_3pn))
  return(blacklist_3pn)
}

DATA_OBJECTS.blacklist_3PN <- UTIL.Assemble3PNDroplist(DATA_OBJECTS.LinearRegressions_DF[,-which(names(DATA_OBJECTS.LinearRegressions_DF) %in% c("thickness~width", "thickness~height", "thickness~diameter"))], SWITCHBOARD.csvMAINFILE)

DATA_OBJECTS.blacklist_2PN_RAWHAND <- c("PARL 319-4-8",
                                        "PARL 325-4-4",
                                        "PARL 325-2-4",
                                        "PARL 390-3-7",
                                        "PARL 390-4-7",
                                        "PARL 572-1-8",
                                        "PARL 572-3-3",
                                        "PARL 580-3-5",
                                        "PARL 584-3-1",
                                        "PARL 839-4-5")

DATA_OBJECTS.blacklist_2PN_CHECK <- UTIL.Collect_ID_NPN(DATA_OBJECTS.LinearRegressions_DF[,-which(names(DATA_OBJECTS.LinearRegressions_DF) %in% c("thickness~width", "thickness~height", "thickness~diameter"))], ">2p/n Threshold")

for (ID in DATA_OBJECTS.blacklist_2PN_RAWHAND) {
  
  if(ID %in% DATA_OBJECTS.blacklist_3PN) {
    cat(paste0("This ID is already flagged as 3PN: [", ID, "]\n"))
  }
  if (!(ID %in% DATA_OBJECTS.blacklist_2PN_CHECK)) {
    cat(paste0("One of the 2PN IDs you input is not an appropriately tagged ID: [", ID, "]. "))
    cat(ifelse(ID %in% DATA_OBJECTS.blacklist_3PN, "Flagged as 3PN datapoint.\n", "Unflagged.\n"))
  }
}


DATA_OBJECTS.csvAUGM_3PN <- UTIL.DropOnNPN(SWITCHBOARD.csvAUGMFILE, DATA_OBJECTS.blacklist_3PN)
DATA_OBJECTS.csvAUGM_2PN <- UTIL.DropOnNPN(DATA_OBJECTS.csvAUGM_3PN, DATA_OBJECTS.blacklist_2PN_CHECK)

print("a")
UTIL.StoreHeatmapsAndFile(SWITCHBOARD.csvAUGMFILE, DATA_OBJECTS.MODELS_intermeasure, "Lin_UNF",   "Heatmaps", SWITCHBOARD.models_intermeasure_abbr)
print("B")
UTIL.StoreHeatmapsAndFile(DATA_OBJECTS.csvAUGM_3PN, DATA_OBJECTS.MODELS_multiplicative, "Mult_UNF",  "Heatmaps", SWITCHBOARD.models_multiplicative_abbr)
UTIL.StoreHeatmapsAndFile(DATA_OBJECTS.csvAUGM_3PN, DATA_OBJECTS.MODELS_multiplicative, "Mult_3PN",  "Heatmaps", SWITCHBOARD.models_multiplicative_abbr)
UTIL.StoreHeatmapsAndFile(DATA_OBJECTS.csvAUGM_3PN, DATA_OBJECTS.MODELS_multiplicative, "Mult_2PN",  "Heatmaps", SWITCHBOARD.models_multiplicative_abbr)
print("c")
UTIL.StoreHeatmapsAndFile(DATA_OBJECTS.csvAUGM_2PN, DATA_OBJECTS.MODELS_elliptical, "Ellip_UNF", "Heatmaps", SWITCHBOARD.models_elliptical_abbr)
UTIL.StoreHeatmapsAndFile(DATA_OBJECTS.csvAUGM_2PN, DATA_OBJECTS.MODELS_elliptical, "Ellip_3PN", "Heatmaps", SWITCHBOARD.models_elliptical_abbr)
UTIL.StoreHeatmapsAndFile(DATA_OBJECTS.csvAUGM_2PN, DATA_OBJECTS.MODELS_elliptical, "Ellip_2PN", "Heatmaps", SWITCHBOARD.models_elliptical_abbr)
# 
# DATA_OBJECTS.MultiplicativeRegressions_DF_3PN <- CALC.ModelGenerator(DATA_OBJECTS.csvAUGM_3PN, DATA_OBJECTS.MODELS_multiplicative)
# 
# DATA_OBJECTS.EllipticalRegressions_DF_3PN <- CALC.ModelGenerator(DATA_OBJECTS.csvAUGM_3PN, DATA_OBJECTS.MODELS_elliptical)
# 
# DATA_OBJECTS.MultiplicativeRegressions_DF_2PN <- CALC.ModelGenerator(DATA_OBJECTS.csvAUGM_2PN, DATA_OBJECTS.MODELS_multiplicative)
# 
# DATA_OBJECTS.EllipticalRegressions_DF_2PN <- CALC.ModelGenerator(DATA_OBJECTS.csvAUGM_2PN, DATA_OBJECTS.MODELS_elliptical)
# 
# 
# 
# DATA_OBJECTS.Lin_R2_UNFILT <- CALC.df_R2(DATA_OBJECTS.LinearRegressions_DF)
# DATA_OBJECTS.Mult_R2_UNFILT <- CALC.df_R2(DATA_OBJECTS.MultiplicativeRegressions_DF_UNFILT)
# DATA_OBJECTS.Ellip_R2_UNFILT <- CALC.df_R2(DATA_OBJECTS.EllipticalRegressions_DF_UNFILT)
# 
# DATA_OBJECTS.Mult_R2_3PN <- CALC.df_R2(DATA_OBJECTS.MultiplicativeRegressions_DF_3PN)
# DATA_OBJECTS.Mult_R2_2PN <- CALC.df_R2(DATA_OBJECTS.MultiplicativeRegressions_DF_2PN)
# 
# DATA_OBJECTS.Ellip_R2_3PN <- CALC.df_R2(DATA_OBJECTS.EllipticalRegressions_DF_3PN)
# DATA_OBJECTS.Ellip_R2_2PN <- CALC.df_R2(DATA_OBJECTS.EllipticalRegressions_DF_2PN)
# 
# DATA_OBJECTS.Mult_SBC_UNFILT <- CALC.df_SBC(DATA_OBJECTS.MultiplicativeRegressions_DF_UNFILT)
# DATA_OBJECTS.Ellip_SBC_UNFILT <- CALC.df_SBC(DATA_OBJECTS.EllipticalRegressions_DF_UNFILT)
# 
# DATA_OBJECTS.Mult_SBC_3PN <- CALC.df_SBC(DATA_OBJECTS.MultiplicativeRegressions_DF_3PN)
# DATA_OBJECTS.Mult_SBC_2PN <- CALC.df_SBC(DATA_OBJECTS.MultiplicativeRegressions_DF_2PN)
# 
# DATA_OBJECTS.Ellip_SBC_3PN <- CALC.df_SBC(DATA_OBJECTS.EllipticalRegressions_DF_3PN)
# DATA_OBJECTS.Ellip_SBC_2PN <- CALC.df_SBC(DATA_OBJECTS.EllipticalRegressions_DF_2PN)
# 
# 
# rownames(DATA_OBJECTS.Lin_R2_UNFILT) <- NULL
# rownames(DATA_OBJECTS.Mult_R2_UNFILT) <- NULL
# rownames(DATA_OBJECTS.Ellip_R2_UNFILT) <- NULL
# 
# rownames(DATA_OBJECTS.Mult_SBC_UNFILT) <- NULL
# rownames(DATA_OBJECTS.Ellip_SBC_UNFILT) <- NULL
# 
# rownames(DATA_OBJECTS.Mult_R2_3PN) <- NULL
# rownames(DATA_OBJECTS.Mult_R2_2PN) <- NULL
# rownames(DATA_OBJECTS.Ellip_R2_3PN) <- NULL
# rownames(DATA_OBJECTS.Ellip_R2_2PN) <- NULL
# 
# rownames(DATA_OBJECTS.Mult_SBC_3PN) <- NULL
# rownames(DATA_OBJECTS.Mult_SBC_2PN) <- NULL
# rownames(DATA_OBJECTS.Ellip_SBC_3PN) <- NULL
# rownames(DATA_OBJECTS.Ellip_SBC_2PN) <- NULL
# 
# 
# #---------------
# test_add_row <- CALC.ModelGenerator_AllAccessions_R2(SWITCHBOARD.csvAUGMFILE, DATA_OBJECTS.MODELS_intermeasure)
# 
# DATA_OBJECTS.Lin_R2_UNFILT <- DATA_OBJECTS.Lin_R2_UNFILT %>%
#   UTIL.AllAccessionToMain(test_add_row)
# #---------------
# 
# 
# 
# #UTIL.StoreHeatmapsAndFile()
# 
# 
# COMPILE.R2heatmap(DATA_OBJECTS.Lin_R2_UNFILT, "Lin_R2_UNFILT", "Heatmaps", SWITCHBOARD.models_intermeasure_abbr)
# COMPILE.R2heatmap(DATA_OBJECTS.Mult_R2_UNFILT, "Mult_R2_UNFILT", "Heatmaps", SWITCHBOARD.models_multiplicative_abbr)
# COMPILE.R2heatmap(DATA_OBJECTS.Ellip_R2_UNFILT, "Ellip_R2_UNFILT", "Heatmaps", SWITCHBOARD.models_elliptical_abbr)
# 
# COMPILE.SBCheatmap(DATA_OBJECTS.Mult_SBC_UNFILT, "Mult_SBC_UNFILT", "Heatmaps", SWITCHBOARD.models_multiplicative_abbr)
# COMPILE.SBCheatmap(DATA_OBJECTS.Ellip_SBC_UNFILT, "Ellip_SBC_UNFILT", "Heatmaps", SWITCHBOARD.models_elliptical_abbr)
# 
# COMPILE.R2heatmap(DATA_OBJECTS.Mult_R2_3PN, "Mult_R2_3PN", "Heatmaps", SWITCHBOARD.models_multiplicative_abbr)
# COMPILE.R2heatmap(DATA_OBJECTS.Mult_R2_2PN, "Mult_R2_2PN", "Heatmaps", SWITCHBOARD.models_multiplicative_abbr)
# COMPILE.R2heatmap(DATA_OBJECTS.Ellip_R2_3PN, "Ellip_R2_3PN", "Heatmaps", SWITCHBOARD.models_elliptical_abbr)
# COMPILE.R2heatmap(DATA_OBJECTS.Ellip_R2_2PN, "Ellip_R2_2PN", "Heatmaps", SWITCHBOARD.models_elliptical_abbr)
# 
# COMPILE.SBCheatmap(DATA_OBJECTS.Mult_SBC_3PN, "Mult_SBC_3PN", "Heatmaps", SWITCHBOARD.models_multiplicative_abbr)
# COMPILE.SBCheatmap(DATA_OBJECTS.Mult_SBC_2PN, "Mult_SBC_2PN", "Heatmaps", SWITCHBOARD.models_multiplicative_abbr)
# COMPILE.SBCheatmap(DATA_OBJECTS.Ellip_SBC_3PN, "Ellip_SBC_3PN", "Heatmaps", SWITCHBOARD.models_elliptical_abbr)
# COMPILE.SBCheatmap(DATA_OBJECTS.Ellip_SBC_2PN, "Ellip_SBC_2PN", "Heatmaps", SWITCHBOARD.models_elliptical_abbr)
# 
# for (df_in in c(DATA_OBJECTS.Mult_R2_3PN,
#                 DATA_OBJECTS.Mult_R2_2PN,
#                 DATA_OBJECTS.Ellip_R2_3PN,
#                 DATA_OBJECTS.Ellip_R2_2PN,
#                 DATA_OBJECTS.Mult_SBC_3PN,
#                 DATA_OBJECTS.Mult_SBC_2PN,
#                 DATA_OBJECTS.Ellip_SBC_3PN,
#                 DATA_OBJECTS.Ellip_SBC_2PN)
#      ) {
#   #print(df_in)
#   #print(paste0("Column Name List: ", colnames(df_in)))
#   for (colname in colnames(df_in)) {
#     #print(paste0("Column Name: ", colname))
#     df_in[[colname]] <- unlist(df_in[[colname]])
#   }
# }
# 
# UTIL.StoreCSV(DATA_OBJECTS.Lin_R2_UNFILT, "Lin_R2_UNFILT", "Heatmaps")
# UTIL.StoreCSV(DATA_OBJECTS.Mult_R2_3PN, "Mult_R2_3PN", "Heatmaps")
# UTIL.StoreCSV(DATA_OBJECTS.Mult_R2_2PN, "Mult_R2_2PN", "Heatmaps")
# UTIL.StoreCSV(DATA_OBJECTS.Ellip_R2_3PN, "Ellip_R2_3PN", "Heatmaps")
# UTIL.StoreCSV(DATA_OBJECTS.Ellip_R2_2PN, "Ellip_R2_2PN", "Heatmaps")
# 
# UTIL.StoreCSV(DATA_OBJECTS.Mult_SBC_3PN, "Mult_SBC_3PN", "Heatmaps")
# UTIL.StoreCSV(DATA_OBJECTS.Mult_SBC_2PN, "Mult_SBC_2PN", "Heatmaps")
# UTIL.StoreCSV(DATA_OBJECTS.Ellip_SBC_3PN, "Ellip_SBC_3PN", "Heatmaps")
# UTIL.StoreCSV(DATA_OBJECTS.Ellip_SBC_2PN, "Ellip_SBC_2PN", "Heatmaps")

#TODO: FIX THE GRAPHS, WRITE THE HARD TABLES, CLEAN UP THE CODE


# TEST FOR ORDERED-NESS OF MODEL DATA INPUT
# for (accession in SWITCHBOARD.ACCESSIONLIST) {
#   model_df <- DATA_OBJECTS.LinearRegressions_DF
#   #print(paste0("Accession: ", accession))
#   for (model in names(model_df)[-1]) {
#     #print(paste0("Model: ", model))
#     modelobject <- CALC.ModelFetch(model_df, accession, model)
#     modelgroups <- names(modelobject$model)
#     #print(all(select(SWITCHBOARD.csvMAINFILE[which(SWITCHBOARD.csvMAINFILE$accession == accession),], modelgroups) == CALC.ModelFetch(model_df, accession, model)$model))
#   }
# }


#]]DEBUG
#ACCESSORY.LMPlotMaker(SWITCHBOARD.csvMAINFILE, DATA_OBJECTS.LinearRegressions_DF, 854, "height", "fresh_weight")


COMPILE.intermeasure(DATA_OBJECTS.LinearRegressions_DF)