# qqGen and Intermeasure Graphing -----------------------------------------


#' @name GRAPHER.qqGen
#' @description Generates a Quantile-Quantile plot for the distribution of a measure for a single accession.
#' @param data_df A dataframe containing all measured data points with IDs and their measures.
#' @param accession A string containing a numerical accession ID.
#' @param measure A string containing the measure of interest.

GRAPHER.qqGen <- function(data_df, accession, measure) {
  target_data <- data_df[[measure]][data_df$accession == accession]
  UTIL.quickPNG(paste0(measure, "--", accession, "_LIN"), "QQPlot_Images")
  qqPlot(target_data, main = paste0(accession, ", ", measure), envelope = 0.95)
  dev.off()
}

#' @name GRAPHER.intermeasure
#' @description Generates a measure vs. measure plot of two measures for an accession, with a fitted linear regression line.
#' @param fits_df A dataframe containing pregenerated models from CALC.ModelGenerator.
#' @param accession A string containing a numerical accession ID.
#' @param modelname A string containing the regression model as text, in the form "y~x"

GRAPHER.intermeasure <- function(fits_df, accession, modelname) {
  #GET x_measure and y_measure from model object
  model_in <- CALC.ModelFetch(fits_df, accession, modelname)
  
  model_in <- UTIL.AugmentModelWithLeverageTagging(model_in)

  model_in <- UTIL.AugmentModelWithID(model_in, accession)
  
  colnames_data <- names(model_in$model)
  model_df <- select(model_in$model, c(colnames_data))
  y_measure <- colnames_data[1]
  x_measure <- colnames_data[2]
  slope <- model_in$coefficients[2]
  intercept <- model_in$coefficients[1]
 
  adj_rsq <- round(summary(model_in)[["adj.r.squared"]], 3)

  intermeasure_plot_out <- ggplot(model_df, aes(!!as.symbol(x_measure), !!as.symbol(y_measure),
                                                label = ifelse(tagged == "N/A", "", ID))) +
    geom_point(aes(color = tagged)) +
    labs(title = (paste0("INTERMEASURE\nMODEL:", modelname, "\nACCESSION:", accession, "\nADJ.R^2:", adj_rsq))) +
    geom_text(hjust=1.05, vjust=0) +
    geom_text(hjust=-.20, vjust=0) +
    geom_abline(intercept = intercept, slope = slope)
  plot(intermeasure_plot_out)
}

# Tukey Comparison and Hypergraphs ----------------------------------------

#' @name GRAPHER.tukeyPlotter
#' @description Generates a .png of a Tukey mean intercomparison interval analysis between all possible pairs of accessions.
#' @param tukey_edgelist A group membership vector generated by CALC.tukeyEdgelist

GRAPHER.tukeyPlotter <- function(tukey_edgelist) {
  tukeyplot <- plot(tukey_edgelist, las=1 , col="gray29")
  show(tukeyplot)
  #return(tukeyplot)
}

#' @name GRAPHER.tukeyHypergraph
#' @description Generates a Hypergraph where accessions with statistically non-significant differences in their means share a hyperedge or group with each other.
#' @param tukey_edgelist A group membership vector generated by CALC.tukeyEdgelist
#' @param measure A string designating the measure to be analyzed - mostly to aid in graph legend generating.

GRAPHER.tukeyHypergraph <- function(tukey_edgelist, measure_string) {
  plot(hypergraph_from_edgelist(tukey_edgelist))
  text(0, 1.25, cex = 1.75, paste0("Hypergraph of ", measure_string))  
}


# Heatmaps of Summary Statistics ------------------------------------------

#' @name GRAPHER.R2heatmap
#' @description Generates a heatmap plot of the adj. R^2 values of all models in a particular model set, fitted over all accessions.
#' @param R2_data_df A dataframe with accession rows and model columns containing adj. R^2 values as doubles.
#' @param abbreviations A vector of string abbreviations for the models for intelligible graphing.

GRAPHER.R2heatmap <- function(R2_data_df, abbreviations) {
  
  R2_heat_palette <- colorRampPalette(brewer.pal(8, "RdYlGn"))(25)
  
  R2_data_df %>%
    setNames(c("accession", abbreviations)) %>%
    column_to_rownames("accession") %>%
    data.matrix() %>%
    heatmap(Rowv = NA, Colv = NA, col = R2_heat_palette)
}

#' @name GRAPHER.SBCheatmap
#' @description Generates a heatmap plot of the SBC values of all models in a particular model set, fitted over all accessions.
#' @param SBC_data_df A dataframe with accession rows and model columns containing SBC values as doubles.
#' @param abbreviations A vector of string abbreviations for the models for intelligible graphing.

  
GRAPHER.SBCheatmap <- function(SBC_data_df, abbreviations) {

  SBC_heat_palette <- rev(colorRampPalette(brewer.pal(8, "RdBu"))(25))
  
  SBC_data_df %>%
    setNames(c("accession", abbreviations)) %>%
    column_to_rownames("accession") %>%
    data.matrix() %>%
    heatmap(Rowv = NA, Colv = NA, scale = "row", col = SBC_heat_palette)
}

