# qqGen and Intermeasure Graphing -----------------------------------------


#' @name GRAPHER.qqGen
#' @description Generates a Quantile-Quantile plot for the distribution of a measure for a single accession.
#' @param data_df A dataframe containing all measured data points with IDs and their measures.
#' @param accession A string containing a numerical accession ID.
#' @param measure A string containing the measure of interest.

GRAPHER.qqGen <- function(data_df, accession, measure) {
  target_data <- data_df[[measure]][data_df$accession == accession]
  UTIL.quickPNG(paste0(measure, "--", accession, "_LIN"), "QQPlot_Images")
  qqPlot(target_data, main = paste0(accession, ", ", measure), envelope = 0.95)
  dev.off()
}

#' @name GRAPHER.intermeasure
#' @description Generates a measure vs. measure plot of two measures for an accession, with a fitted linear regression line.
#' @param fits_df A dataframe containing pregenerated models from CALC.ModelGenerator.
#' @param accession A string containing a numerical accession ID.
#' @param modelname A string containing the regression model as text, in the form "y~x"

GRAPHER.intermeasure <- function(fits_df, accession, modelname) {
  #GET x_measure and y_measure from model object
  model_in <- CALC.ModelFetch(fits_df, accession, modelname)
  
  model_in <- UTIL.AugmentModelWithLeverageTagging(model_in)

  model_in <- UTIL.AugmentModelWithID(model_in, accession)
  
  colnames_data <- names(model_in$model)
  model_df <- select(model_in$model, c(colnames_data))
  y_measure <- colnames_data[1]
  x_measure <- colnames_data[2]
  slope <- model_in$coefficients[2]
  intercept <- model_in$coefficients[1]
 
  adj_rsq <- round(summary(model_in)[["adj.r.squared"]], 3)

  intermeasure_plot_out <- ggplot(model_df, aes(!!as.symbol(x_measure), !!as.symbol(y_measure),
                                                label = ifelse(tagged == "N/A", "", ID))) +
    geom_point(aes(color = tagged)) +
    xlab(x_measure) +
    ylab(y_measure) +
    labs(title = (paste0("INTERMEASURE\nMODEL:", modelname, "\nACCESSION:", accession, "\nADJ.R^2:", adj_rsq))) +
    geom_text(hjust=1.05, vjust=0) +
    geom_text(hjust=-.20, vjust=0) +
    geom_abline(intercept = intercept, slope = slope)
  plot(intermeasure_plot_out)
}

#' @name GRAPHER.ViolinPlot
#' @description Generates a Violin plot of the range of valus of a measure over all accessions.
#' @param data_df The table of measure values by individual pads.
#' @param measure The specific measure of interest in the data table.

GRAPHER.ViolinPlot <- function(data_df, measure) {
  violin_plot <- ggplot(data_df, aes(get(measure), as.factor(accession), fill = as.factor(accession))) +
    geom_violin(trim=F, show.legend = F) +
    geom_boxplot(width = 0.2) +
    xlab(measure) +
    ylab("Accession") + 
    ggtitle(paste0("Distribution of ", measure, " by Accession")) + 
    theme(legend.position = "none")
  plot(violin_plot)
}

# Tukey Comparison and Hypergraphs ----------------------------------------

#' @name GRAPHER.tukeyPlotter
#' @description Generates a .png of a Tukey mean intercomparison interval analysis between all possible pairs of accessions.
#' @param tukey_edgelist A group membership vector generated by CALC.tukeyEdgelist

GRAPHER.tukeyPlotter <- function(tukey_edgelist) {
  tukeyplot <- plot(tukey_edgelist, las=1 , col="gray29")
  show(tukeyplot)
  #return(tukeyplot)
}

#' @name GRAPHER.tukeyHypergraph
#' @description Generates a Hypergraph where accessions with statistically non-significant differences in their means share a hyperedge or group with each other.
#' @param tukey_edgelist A group membership vector generated by CALC.tukeyEdgelist
#' @param measure A string designating the measure to be analyzed - mostly to aid in graph legend generating.

GRAPHER.tukeyHypergraph <- function(tukey_edgelist, measure_string) {
  plot(hypergraph_from_edgelist(tukey_edgelist))
  text(0, 1.25, cex = 1.75, paste0("Hypergraph of ", measure_string))  
}


# Heatmaps of Summary Statistics ------------------------------------------

#' @name GRAPHER.R2heatmap
#' @description Generates a heatmap plot of the adj. R^2 values of all models in a particular model set, fitted over all accessions.
#' @param R2_data_df A dataframe with accession rows and model columns containing adj. R^2 values as doubles.
#' @param heatmap_title A string with the title of the heatmap.
#' @param abbreviations A vector of string abbreviations for the models for intelligible graphing.

GRAPHER.R2heatmap <- function(R2_data_df, heatmap_title, abbreviations) {
  
  if (!(is.vector(abbreviations))) {
    abbreviations <- abbreviations$models
  }
  
  heatmap_plot <- R2_data_df %>%
    `colnames<-`(c("accession", abbreviations)) %>%
    pivot_longer(cols = -1, names_to = "models", values_to = "values") %>%
    mutate(models = factor(models, levels = abbreviations)) %>%
    ggplot(aes(as.factor(models), as.factor(accession), fill = values)) +
      geom_tile() +
      xlab("Models") +
      ylab("Accession") +
      ggtitle(heatmap_title) +
      theme(axis.text.x = element_text(angle = 60, vjust = 0, hjust=0)) +
      scale_fill_viridis(direction = -1, begin = max(R2_data_df[-1]), end = ifelse(min(R2_data_df[-1]) < 0, 0, min(R2_data_df[-1])))
  print(heatmap_plot)
}

#' @name GRAPHER.SBCheatmap
#' @description Generates a heatmap plot of the SBC values of all models in a particular model set, fitted over all accessions.
#' @param SBC_data_df A dataframe with accession rows and model columns containing SBC values as doubles. 
#' @param heatmap_title A string with the title of the heatmap.
#' @param abbreviations A vector of string abbreviations for the models for intelligible graphing.
  
GRAPHER.SBCheatmap <- function(SBC_data_df, heatmap_title, abbreviations) {

  if (!(is.vector(abbreviations))) {
    abbreviations <- abbreviations$models
  }
  
  normal_table_by_row <- function(table_in) {
    for (row in c(1:nrow(table_in))) {
      vector_in <- table_in[row,]
      table_in[row,] <- (vector_in-min(vector_in))/max(vector_in)
      table_in[row,] <- table_in[row,] * 1/max(table_in[row,])
    }
    return(table_in)
  }

  
  heatmap_plot <- SBC_data_df %>%
    `rownames<-`(c(SWITCHBOARD.ACCESSIONLIST, "All")) %>%
    `colnames<-`(c("accession", abbreviations)) %>%
    {.[-1]} %>%
    normal_table_by_row() %>%
    rownames_to_column("accession") %>%
    `rownames<-`(rownames(SBC_data_df)) %>%
    pivot_longer(cols = -1, names_to = "models", values_to = "values") %>%
    mutate(models = factor(models, levels = abbreviations)) %>%
    ggplot(aes(models, as.ordered(accession), fill = values)) +
      geom_tile() +
      xlab("Models") +
      ylab("Accession") +
      ggtitle(heatmap_title) +
      theme(axis.text.x = element_text(angle = 60, vjust = 0, hjust=0)) +
      scale_fill_viridis(direction = -1, option = "A")
  print(heatmap_plot)
}




# 3D Scatterplots ---------------------------------------------------------

GRAPHER.3DScatterPlot <- function(data_df, x_axis, y_axis, z_axis) {
  plotpalette_3D <- c("#009a00", # Green
                      "#ef1101", # Bright Red
                      "#5c0300", # Burgundy
                      "#fd9206", # Pale Orange
                      "#a45d00", # Light Brown
                      "#fef636", # Pale Yellow
                      "#8f8a00", # Dirty Yellow
                      "#0006a4", # Dark Blue
                      "#0efd0e", # Bright Green
                      "#010afb", # Bright Blue
                      "#ba20fd", # Lavender
                      "#7600a8", # Purple
                      "#080f0f", # Black
                      "#faffff"  # White
                      ) #Fix these colors later
  
  print(data_df["width"])
  
  accession_vector <- data_df$accession
  x_axis <- data_df[x_axis]
  y_axis <- data_df[y_axis]
  z_axis <- data_df[z_axis]

  plot_ly(x = x_axis, y = y_axis, z = z_axis, color = as.factor(accession_vector), colors =  plotpalette_3D)
}
